// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://coqaiwjpmgfkonlymtbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_656kn__SFDA4ayT0IPpVFQ_kyjkJ9RN";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const hasSupabase = !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;

console.log("[SupabaseClient] SUPABASE_URL:", SUPABASE_URL ? "Configured" : "Not Configured");
console.log("[SupabaseClient] SUPABASE_PUBLISHABLE_KEY:", SUPABASE_PUBLISHABLE_KEY ? "Configured" : "Not Configured");
console.log("[SupabaseClient] hasSupabase:", hasSupabase);